version: "3.7"
services:
  app:
    build:
      context: ./
    container_name: crawler-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - crawler

  nginx:
    image: nginx:alpine
    container_name: crawler-nginx
    restart: unless-stopped
    ports:
      - 8000:8080
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - crawler

networks:
  crawler:
    driver: bridge
